2021-08-31 15:11:01 database: wrong user or password; user: ""
org.h2.message.DbException: Wrong user name or password [28000-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.engine.Engine.openSession(Engine.java:131)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at com.wisecoders.dbs.rdbms.connect.model.envoy.Envoy.q(Envoy.java:56)
	at com.wisecoders.dbs.rdbms.connect.model.envoy.Envoy.a(Envoy.java:87)
	at com.wisecoders.dbs.rdbms.connect.fx.FxTestConnectivityTask.a(FxTestConnectivityTask.java:47)
	at com.wisecoders.dbs.rdbms.connect.fx.FxTestConnectivityTask.call(FxTestConnectivityTask.java:20)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: org.h2.jdbc.JdbcSQLInvalidAuthorizationSpecException: Wrong user name or password [28000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:461)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 23 more
2021-08-31 15:11:39 jdbc[3]: exception
org.h2.jdbc.JdbcSQLFeatureNotSupportedException: Feature not supported: "getFunctions" [50100-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:507)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.getUnsupportedException(DbException.java:269)
	at org.h2.message.TraceObject.unsupported(TraceObject.java:398)
	at org.h2.jdbc.JdbcDatabaseMetaData.getFunctions(JdbcDatabaseMetaData.java:3273)
	at com.wisecoders.dbs.rdbms.reverseEngineer.model.ImporterUtils.c(ImporterUtils.java:150)
	at com.wisecoders.dbs.rdbms.Rdbms.listFunctionNames(Rdbms.java:445)
	at com.wisecoders.dbs.rdbms.reverseEngineer.model.StructureImporter.a(StructureImporter.java:54)
	at com.wisecoders.dbs.rdbms.reverseEngineer.model.StructureImporter.<init>(StructureImporter.java:21)
	at com.wisecoders.dbs.rdbms.reverseEngineer.fx.FxImportStructureTask$1.<init>(FxImportStructureTask.java:40)
	at com.wisecoders.dbs.rdbms.reverseEngineer.fx.FxImportStructureTask.a(FxImportStructureTask.java:40)
	at com.wisecoders.dbs.rdbms.reverseEngineer.fx.FxImportStructureTask.call(FxImportStructureTask.java:14)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
2021-08-31 15:11:39 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "triggers" not found; SQL statement:
SELECT trigger_name FROM INFORMATION_SCHEMA.triggers WHERE trigger_schema='PUBLIC' [42102-200]
2021-08-31 15:11:39 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "sequences" not found; SQL statement:
SELECT sequence_name, 'START WITH '||(current_value+1) FROM INFORMATION_SCHEMA.sequences WHERE sequence_schema='PUBLIC' [42102-200]
2021-08-31 15:11:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "constraints" not found; SQL statement:
SELECT table_name, constraint_name, check_expression FROM INFORMATION_SCHEMA.constraints WHERE check_expression IS NOT NULL AND constraint_schema='PUBLIC' [42102-200]
